server:
  port: 9090

spring:
  cloud:
    config:
      name: product-catalog
      uri: http://localhost:8888
      failFast: false

management:
  endpoint:
    web:
      refresh:
        enabled: true
  endpoints:
    actuator:
      enabled: true
    web:
      exposure:
        include: '*'